-- CreateEnum
CREATE TYPE "BlocksTypes" AS ENUM ('MEETING_TYPE_SELECT', 'AGENDA_BLOCK', 'AGENDA_LIST', 'AGENDA_ITEM', 'ATTENDEES_BLOCK', 'ATTENDEES_LIST', 'ATTENDEES_ITEM', 'MEETING_DETAILS_BLOCK', 'MEETING_TIME', 'MEETING_DURATION', 'MEETING_LOCATION', 'MEETING_DATE', 'MEETING_TITLE', 'MEETING_PREREQUISITES');

-- AlterTable
ALTER TABLE "MeetingNote" ALTER COLUMN "additionalBlocks" SET DEFAULT '[]';
